### PR TITLE
Update example to use 2.1.6

### PR DESCRIPTION
**Pull request by shakyShane**
Just showing the minimum config needed

### CODE REVIEW

**Comment by zanona** [comment]
Thanks man

**Comment by zanona** [comment]
@shakyShane Weird, apparently without `tagNames: { "less": "link"}` it is not doing the trick for me. How about you?

**Comment by shakyShane** [comment]
Hmm works fine for me. did you `npm rm browser-sync && npm install browser-sync` ?

**Comment by zanona** [comment]
Sorry, it works correctly it might have been cache or something. All smooth now :+1:  Thanks again

**Comment by shakyShane** [comment]
Wickid!

**Pull request merged**
